require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, min_ios_version_supported
install! 'cocoapods', :deterministic_uuids => false

target 'project_v1' do
  config = use_native_modules!

  # Podstawowe ustawienia RN
  use_react_native!(
    :path           => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath]
    )
  end
end
